PIH/openmrs-module-pihcore

- api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoAddressBundle.java
- api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoMetadataBundle.java
- api/src/main/resources/addresshierarchy/mexico_address_hierarchy_entries_1.csv
https://tickets.pih-emr.org/browse/MEX-6
This adds address hierarchy entries; changes address format.
This includes "Otro" (Other) as an option for Community.
This also seems to add a field called something like "Rapidly search for an address" that seems quite redundant with the Community field itself. Eventually we'll probably want to get rid of that.
> MEX-6: Address should have fields "community" and "directions"

- api/src/main/resources/messages.properties
- omod/src/main/webapp/resources/htmlforms/mexico/consult.xml
In brief:
- chill out the error color a bit
- make it so that valid values don't turn green (MEX-322 Research disabling red/green shading on numeric form fields)
- add last subjective and lab order text to the left of subjective box (MEX-253 Previous "Subjective" field entry should be visible next to form entry box, MEX-273 Contents of previous "Lab tests" box should appear next to "Subjective")
- add previous values to asthma (except for "nighttime symptoms," because the diagnosis constructs make this impossible. I also wonder about how one can represent these in dashboard widgets.)
- add previous values to diabetes
- add a button to epilepsy that the user needs to click in order to change the baseline value
- and, the best part: incremental show/hide buttons for medications. I'm opening …
> Make a bunch of improvements to the Mexico consult form

- api/src/main/resources/liquibase.xml
@mogoodrich Pull request.  These command have no prerequisite since they should be on all PIH EMR instances.  It's possible that they are already set properly, but these sql changes can be run again with no problems.
These reset the preferred name for "Serum Glucose" in English and French.
> UHM-3974 Liquibase changeset for serum glucose

- api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/concept/AnswerConcepts.java
- api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/concept/CommonConcepts.java
- api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/concept/SocioEconomicConcepts.java
This adds names to the MDD concepts. I did this before I found out that
those names don't seem to do anything -- the names used in the reg form
are in messages.properties.
> MEX-404 Registration form elements should be in Spanish

- api/src/main/java/org/openmrs/module/pihcore/PihCoreActivator.java
- api/src/main/java/org/openmrs/module/pihcore/PihCoreConstants.java
- api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/EncounterRoleBundle.java
@mseaton and @mogoodrich , here is the PR for creating a CommCare user with credentials specified in the openmrs-runtime.properties. Does this make sense to you? Thanks!
> CCI-43, add commcare user

- omod/src/main/webapp/pages/visit/templates/sections/defaultPlanSectionActions.gsp
- omod/src/main/webapp/pages/visit/templates/sections/defaultSectionActions.gsp
I added a div in the appropriate files which included a class (pull-rigth) allowing to align the actions section on the right.
please accept my pull request.
@mogoodrich @lnball @mseaton
> Align template icons (expand, edit) on visit page

- api/src/main/java/org/openmrs/module/pihcore/PihCoreConstants.java
- api/src/main/java/org/openmrs/module/pihcore/config/Components.java
- api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/EncounterTypeBundle.java
- api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/program/OVCProgramBundle.java
- api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/program/PihProgramsBundle.java
- api/src/main/java/org/openmrs/module/pihcore/metadata/core/EncounterTypes.java
- api/src/main/java/org/openmrs/module/pihcore/metadata/core/program/OVCProgram.java
This creates a stub for the OVC program, as well as the encounter types for the intake and follow-up forms.
Relates to
[UHM-4979 OVC Intake form](https://pihemr.atlassian.net/browse/UHM-4979)
[UHM-4986 OVC Program config](https://pihemr.atlassian.net/browse/UHM-4986)
> Create metadata for OVC program

- omod/src/main/webapp/resources/scripts/visit/filters.js
@mogoodrich , I am wondering how this ever worked? Maybe it stopped working after we pull out the encounterTypeConfig from pihcore?
> UHM-5119, show encounter types on visit list

- api/pom.xml
Use the explicit snapshot versions. These are kept up to date by the release job: https://github.com/PIH/openmrs-config-pihemr/pull/235 . The latter commit on this PR was made by the release job.
> Don't use LATEST version for config repos

- api/src/main/java/org/openmrs/module/pihcore/config/Config.java
- api/src/main/java/org/openmrs/module/pihcore/config/ConfigDescriptor.java
- omod/src/main/java/org/openmrs/module/pihcore/page/controller/PatientPageController.java
UHM-5404 - Adds 2 features to support this ticket.  1. Adds a new page controller that supports passing a patient identifier and type, and a particular set of configurations, to open a patient dashboard for a patient with that identifier.  2.  Adds the ability to add arbitrary extensions via PIH config as an alternative to doing this programmatically in the CALF.
> UHM-5404 - Adds 2 features to support this ticket.

- omod/src/main/webapp/pages/visit/templates/encounters/defaultEncounterHeading.gsp
- omod/src/main/webapp/pages/visit/templates/encounters/vitalsEncounterHeading.gsp
- omod/src/main/webapp/pages/visit/templates/visitDetails.gsp
- omod/src/main/webapp/resources/scripts/visit/constants.js
Depends on https://github.com/openmrs/openmrs-module-uicommons/pull/98
English:
Spanish:
French:
Still displays in English for Haitian, but that's not actually a regression, because these have always displayed in English. They'll start displaying in French format next year, pending a Unicode update.
> Localized formatting of dates in the visit note

- omod/src/main/webapp/pages/visit/templates/sections/primaryCarePlanSectionHeading.gsp
- omod/src/main/webapp/resources/scripts/visit/constants.js
- omod/src/main/webapp/resources/scripts/visit/filters.js
- omod/src/main/webapp/resources/scripts/visit/visit.js
This is for displaying medication orders concept names in the encounter header:
> SL-414, display drug orders concepts in the encounter header

- api/src/main/java/org/openmrs/module/pihcore/apploader/apps/patientregistration/SectionsDefault.java
- api/src/main/java/org/openmrs/module/pihcore/apploader/apps/patientregistration/SectionsSierraLeone.java
- api/src/main/java/org/openmrs/module/pihcore/config/registration/RegistrationConfigDescriptor.java
The default address section was excluding the country field when displaying the address. So, I had to overwrite this method in the SierraLeone class.
> UHM-7478, in Sierra Leone display template should include country

- api/src/main/java/org/openmrs/module/pihcore/printer/template/SLWristbandTemplate.java
- api/src/main/java/org/openmrs/module/pihcore/printer/template/ZLWristbandTemplate.java
- api/src/test/java/org/openmrs/module/pihcore/printer/template/WristbandComponentTest.java
- api/src/test/java/org/openmrs/module/pihcore/printer/template/ZLWristbandTemplateTest.java
- omod/src/main/java/org/openmrs/module/pihcore/fragment/controller/WristbandFragmentController.java
@mogoodrich , I just created a separate template for implementing the requirements for the MCOE printing. For now I just copied the existing template from Mirebalais and deleted the fields that are not required at MCOE. Now, the Print Wristband action is visible in KGH Test instance and clicking print won't cause a stacktrace. I am going to continue to work on implementing the exact fields required at MCOE, but first just wanted to make sure this is the right approach? Thanks!
> UHM-7589, add wristband template for Sierra Leone EMR

- api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java
Here we go again.  Greatly simplified.
- Added 1 live checkin maternal form for SL only where the location tag is 'Check-In Maternal Location'
- Rest is unchanged
But still need to change the homepage app to use the Maternal checkin form if the location is 'MCOE Triage'.  Suggestions @mogoodrich
> SL-469 Added 1 Maternal checkin form for MCOE

- api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java
Just configured the Las Checkin Encounter widget on the registration summary page to search for multiple encounter types.
> SL-480: configure last check-in encounter to search for multiple encounter types

- .gitignore
- omod/src/main/webapp/pages/visit/templates/encounters/defaultHtmlFormEncounterLong.gsp
- omod/src/main/webapp/resources/scripts/visit/visit.js
@mogoodrich , in this PR I have added another field to the template section that is an array of fields with values. So, before I made this change here is how the templateModel data looked like:
{
"name": "Maternal Check-In",
"fields": [
{
"name": "Reason for visit",
"datatype": "coded",
"value": "Family planning services"
},
{
"name": "Patient referred to hospital",
"datatype": "coded",
"value": "Yes"
},
{
"name": "Role of referring person",
"datatype": "coded",
"value": "Peripheral Health Unit"
},
{
"name": "Other referral (text)",
"datatype": "text",
"value": ""
},
{
"name": "Address of contact person",
"datatype": "text",
"value": ""
},
{
"name": "Telephone number of contact",
"datatype": "text",
"value": ""
},
{
"name": "Reasons for referral (coded)",
"datatype": "coded",
"value": "" …
> UHM-7748, display only obs with values

- api/src/main/java/org/openmrs/module/pihcore/htmlformentry/action/AddPatientToQueueAction.java
- api/src/test/java/org/openmrs/module/pihcore/action/AddPatientToQueueActionTest.java
@mogoodrich , while testing this MCOE check-in form, I have noticed a strange error. If I go back to a past visit which had MCOE check-in encounter with Refer to MCOE Triage check-in obs, and try to edit the encounter then the postsubmit action is executed again and another queue entry is created on the past visit:
When I click to edit the MCOE Check-in encounter, the Refer to MCOE triage question is not displayed, because of this code:
https://github.com/PIH/openmrs-config-pihsl/blob/master/configuration/pih/htmlforms/checkinMaternal.xml#L259
<ifMode mode="ENTER" include="true">
<includeIf velocityTest="($visit.open)">
<fieldset class="queue">
<legend>
<uimessage code="MCOE Triage"/>
</legend>
<h3>
<uimessage code="MCOE Triage"/>
</h3>
<p class="left">
<obs conceptId="CIEL:1272" …
> UHM-7716: prevent adding queue entries for past visits

- api/src/main/java/org/openmrs/module/pihcore/reporting/dataset/manager/ConsultationsDataSetManager.java
Use the generic mapping for Date of Death.  This will be useful when we move to datetime.  I believe the same code will work for datetime (as it does now for date).
> SL-511 Change concept mapping for date of death for reporting

- api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java
- api/src/main/java/org/openmrs/module/pihcore/htmlformentry/action/AddPatientToQueueAction.java
I just added to the existing AddPatientToQueueAction the ability to set the queue entry priority via another hidden coded question that could be set automatically based on the triage symptoms.
> SL-553: add ability to set queue entry priority

- omod/src/main/java/org/openmrs/module/pihcore/fragment/controller/dashboardwidgets/ObsByEncounterFragmentController.java
- omod/src/main/webapp/fragments/dashboardwidgets/obsByEncounter.gsp
I was able to enhance the existing ObsByEncounter widget to display the temperatures as it is spec out in SL-741:
here is the dashboard config:
> SL-741: enhance the ObsByEncounter widget to display numeric obs with abnormal values

- omod/src/main/webapp/pages/visit/templates/encounters/clinicConsultLong.gsp
- omod/src/main/webapp/pages/visit/templates/sections/dxLong.gsp
- omod/src/main/webapp/pages/visit/templates/sections/dxSectionHeading.gsp
I think these are the only templates that needed to be modified to display the non-coded dx. Please let me know if I miss any. Maybe the best way to test this update is to deploy it to humci to see if there are other encounter templates that needed to be modified.
> UHM-8220: display non-coded dx in the view mode

- .gitignore
- omod/src/main/webapp/fragments/dashboardwidgets/appointments.gsp
- omod/src/main/webapp/fragments/dashboardwidgets/discreteValues.gsp
- omod/src/main/webapp/fragments/dashboardwidgets/encounters.gsp
- omod/src/main/webapp/fragments/dashboardwidgets/labResults.gsp
- omod/src/main/webapp/fragments/dashboardwidgets/medsDispensed.gsp
- omod/src/main/webapp/fragments/dashboardwidgets/newbornIndicators.gsp
- omod/src/main/webapp/fragments/dashboardwidgets/obsByEncounter.gsp
- omod/src/main/webapp/fragments/dashboardwidgets/patientLocation.gsp
- omod/src/main/webapp/fragments/dashboardwidgets/statusData.gsp
Add html class names to various widgets. This makes is easier to select and hide them when embedding the O2 pregnancy dashboard into an O3 workspace.
For widgets that are configurable to show different data (like the encounters widget), I added `${app.id}` (ex: "pregnancy.dashboard.ancInitialEncounters") as a class name. For widgets that are not configurable to show different data (like the appointments widget) I just hard-coded a string.
I'll make a corresponding PR for widgets in `opnmrs-module-coreapps` as well.
> (chore) UHM-8241 - add html classes to various widgets

- omod/pom.xml
- pom.xml
Doing a `mvn dependency:tree` on pihcore shows that com.fasterxml.jackson.core:jackson-core:jar:2.14.1 is provided by OpenMRS core.
So this removes the (older) org.codehaus.jacson version 1.9.13 libraries that I think we had for some sort of attempt at compatibility with older versions of some openmrs modules at one point, but which doesn't seem needed any longer.
Building passes fine with these removed.
> UHM-8292 - Remove old Jackson version

- api/src/main/java/org/openmrs/module/pihcore/search/PihPatientSearchAlgorithm.java
- api/src/test/java/org/openmrs/module/pihcore/search/PihPatientSearchAlgorithmTest.java
- api/src/test/resources/searchTestDataset.xml
@mogoodrich , here is the fix for the NPE when potential matches have no birthdate. I created a unit test and was able to reproduce the NPE we were seeing in humci yesterday before you cleaned up the test data. Thanks for reviewing!
> UHM-8591: prevent NPE when patient has no birthdate

- api/src/main/java/org/openmrs/module/pihcore/task/PihCoreScheduledTaskExecutor.java
- api/src/main/java/org/openmrs/module/pihcore/task/PihRemovePatientsFromMCOEQueue.java
- api/src/test/java/org/openmrs/module/pihcore/task/PihRemovePatientsFromMCOEQueueTest.java
- api/src/test/resources/mcoeTriageQueueTestDataset.xml
@mseaton , please let me know if this is the right direction for removing timeout entries from the MCOE triage queue. I will add unit tests and more configuration if necessary? Thanks!
> SL-983: remove entries older than 12 hours from the MCOE triage queue

- api/src/main/java/org/openmrs/module/pihcore/task/PihRemovePatientsFromMCOEQueue.java
@mseaton , this change would allow removing from the queue valid entries which are not duplicate. Maybe because of the previous bug addressed in https://openmrs.atlassian.net/browse/O3-4985 duplicate entries may be present in the queue and therefore the entire code below was not executing if the duplicate entry happened to be the first entry processed.
> SL-983: one duplicate entry should not prevent removing other entries from the queue
