PIH/openmrs-module-pihcore

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoLocationsBundle.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoMetadataBundle.java
api/src/main/java/org/openmrs/module/pihcore/identifier/mexico/ConfigureMexicoIdGenerators.java
api/src/main/java/org/openmrs/module/pihcore/metadata/mexico/MexicoLocations.java
api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java

https://tickets.pih-emr.org/browse/MEX-36
Adds all the Chiapas clinic locations, as well as our hub, to MexicoLocations. A few tags are added to all of them, probably not all that will be needed.

Add all Mexico locations with a few LocationTags

---

omod/src/main/webapp/resources/htmlforms/mexico/checkin.xml

More conversation will be had about the ideal UI & fields for this, but for now, this will allow the user to access the patient visit page.

Create a check-in form based off Haiti, sans payment stuff

---

api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java

https://tickets.pih-emr.org/browse/MEX-54

MEX-54: First step using existing primaryCare system

---

api/src/main/java/org/openmrs/module/pihcore/config/Components.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/EncounterTypeBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/core/EncounterTypes.java
omod/src/main/webapp/resources/htmlforms/mexico/clinic-followup.xml
omod/src/main/webapp/resources/htmlforms/mexico/clinic-initial.xml
omod/src/main/webapp/resources/scripts/visit/constants.js
omod/src/main/webapp/resources/scripts/visit/encounterTypeConfig.js

https://tickets.pih-emr.org/browse/MEX-68

MEX-68: Fork primaryCare into a new component

---

api/src/main/java/org/openmrs/module/pihcore/config/Components.java

https://tickets.pih-emr.org/browse/MEX-109

MEX-109: Add BP widget to patient dashboard

---

api/src/main/java/org/openmrs/module/pihcore/PihCoreConstants.java
api/src/main/java/org/openmrs/module/pihcore/config/Components.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/RolesAndPrivilegesBundle.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/program/HypertensionProgramBundle.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/program/PihProgramsBundle.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoMetadataToInstallAfterConceptsBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/core/program/HypertensionProgram.java
api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java

https://tickets.pih-emr.org/browse/MEX-110
The diff noise should be concentrated in "Sorting and cleaning" -- I'd look at https://github.com/PIH/openmrs-module-pihcore/commit/4c14eabea9f037673670775868e6e9496d52a2a2 for a good view of the changes.

MEX-110: Make BP widget only show for hypertension patients

---

omod/src/main/webapp/resources/scripts/visit/encounterTypeConfig.js

https://tickets.pih-emr.org/browse/MEX-99

MEX-99 Remove History and Exam from templates

---

omod/src/main/webapp/pages/visit/templates/sections/mexico/planSectionHeading.gsp
omod/src/main/webapp/pages/visit/templates/sections/mexico/planSectionShort.gsp
omod/src/main/webapp/resources/htmlforms/mexico/section-plan.xml
omod/src/main/webapp/resources/scripts/visit/constants.js
omod/src/main/webapp/resources/scripts/visit/encounterTypeConfig.js

https://tickets.pih-emr.org/browse/MEX-112

MEX-112: Make Lab Tests into a free text box

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoLocationsBundle.java
api/src/main/java/org/openmrs/module/pihcore/identifier/mexico/ConfigureMexicoIdGenerators.java
api/src/main/java/org/openmrs/module/pihcore/metadata/mexico/MexicoLocations.java
api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java
api/src/main/java/org/openmrs/module/pihcore/setup/MetadataMappingsSetup.java
api/src/main/java/org/openmrs/module/pihcore/setup/PatientIdentifierSetup.java

https://tickets.pih-emr.org/browse/MEX-17

MEX-17: Patient Identifier for CES

---

omod/src/main/webapp/resources/htmlforms/mexico/section-plan.xml

https://tickets.pih-emr.org/browse/MEX-114

MEX-114 Remove Disposition section

---

api/src/main/java/org/openmrs/module/pihcore/PihCoreConstants.java
api/src/main/java/org/openmrs/module/pihcore/config/Components.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/program/DiabetesProgramBundle.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/program/PihProgramsBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/core/program/DiabetesProgram.java

https://tickets.pih-emr.org/browse/MEX-147

MEX-147: Should be easy to view patient diabetes clinical history

---

api/src/main/resources/messages.properties
omod/src/main/webapp/resources/htmlforms/mexico/section-plan.xml

https://tickets.pih-emr.org/browse/MEX-115

MEX-115 Add Approximate Next Appt Date

---

api/src/main/java/org/openmrs/module/pihcore/config/registration/SocialConfigDescriptor.java
omod/src/main/webapp/resources/htmlforms/mexico/patientRegistration-social.xml

MEX-120 Add yes/no concepts to Registration: Disabled, Can Read
https://tickets.pih-emr.org/browse/MEX-120
Depends on https://github.com/PIH/openmrs-module-mirebalaismetadata/pull/11

MEX-120 Add yes/no concepts to Registration: Disabled, Can Read

---

api/src/main/java/org/openmrs/module/pihcore/config/Components.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoMetadataToInstallAfterConceptsBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/core/program/MCHProgram.java
api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java

MEX-207 Enable Mental Health program for CES
https://tickets.pih-emr.org/browse/MEX-207
Also includes some comments -- the beginnings of documenting what our components actually do.

MEX-207 Enable Mental Health program for CES

---

api/src/main/java/org/openmrs/module/pihcore/PihCoreConstants.java
api/src/main/java/org/openmrs/module/pihcore/config/Components.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/program/AsthmaProgramBundle.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoMetadataToInstallAfterConceptsBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/core/program/AsthmaProgram.java

MEX-237 Create minimal Asthma program
https://tickets.pih-emr.org/browse/MEX-237

MEX-237 Create minimal Asthma program

---

api/src/main/java/org/openmrs/module/pihcore/PihCoreConstants.java
api/src/main/java/org/openmrs/module/pihcore/config/Components.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/program/EpilepsyProgramBundle.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoMetadataToInstallAfterConceptsBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/core/program/EpilepsyProgram.java

MEX-236 Create minimal Epilepsy program
https://tickets.pih-emr.org/browse/MEX-236

MEX-236 Create minimal Epilepsy program

---

api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java

Enable edTriage, edTriageQueue and edConsult for Kouka -- Harper -- JJ Dossen

Enable edTriage, edTriageQueue and edConsult for Kouka

---

api/src/main/resources/messages.properties
omod/src/main/webapp/resources/htmlforms/mexico/consult.xml
omod/src/main/webapp/resources/htmlforms/mexico/vitals.xml

https://tickets.pih-emr.org/browse/MEX-165
https://tickets.pih-emr.org/browse/MEX-202
https://tickets.pih-emr.org/browse/MEX-161

MEX-161, MEX-165, MEX-202: no imperial units; subjective box on consult form

---

api/src/main/java/org/openmrs/module/pihcore/PihCoreConstants.java
api/src/main/java/org/openmrs/module/pihcore/config/Components.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/program/MalnutritionProgramBundle.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/program/PihProgramsBundle.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoMetadataToInstallAfterConceptsBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/core/program/MalnutritionProgram.java

MEX-242 Create minimal Malnutrition program
https://tickets.pih-emr.org/browse/MEX-242

MEX-242 Create minimal Malnutrition program

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoPatientIdentifierTypeBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/mexico/MexicoPatientIdentifierTypes.java

MEX-119 Add CURP to Registration
https://tickets.pih-emr.org/browse/MEX-119

MEX-119 Add CURP to Registration

---

omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

https://tickets.pih-emr.org/browse/MEX-22

MEX-22 CES Physical Exam note

---

omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

https://tickets.pih-emr.org/browse/MEX-332

MEX-332 Remove Visit Information section from CES Consult Note

---

omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

https://tickets.pih-emr.org/browse/MEX-148
Depends on https://github.com/openmrs/openmrs-module-htmlformentry/pull/147
Also move Asthma above Diabetes

MEX-148 Consult form should display forms for programs depending on program enrollment status

---

.tx/config
api/src/main/resources/messages_es.properties

I won't bother you with reviewing translation updates in the future, I just wanna make sure I'm doing this right :)
I used `tx pull -l es`

MEX-268 More intuitive names on the Clinical Dashboard

---

api/src/main/resources/messages.properties
omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

MEX-282 Analysis Clinical Note should be above Diagnoses

---

api/src/main/resources/messages.properties
omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

https://tickets.pih-emr.org/browse/MEX-168

MEX-168 Asthma form should ask a different question for children

---

api/src/main/java/org/openmrs/module/pihcore/PihCoreConstants.java
api/src/main/java/org/openmrs/module/pihcore/config/Components.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/program/ANCProgramBundle.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/program/PihProgramsBundle.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoMetadataToInstallAfterConceptsBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/core/program/ANCProgram.java
omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

https://pihemr.atlassian.net/browse/MEX-314

MEX-314 Switch CES from using MCH Program to ANC Program

---

api/src/main/resources/messages.properties
omod/src/main/webapp/resources/htmlforms/sierra_leone/vitals.xml

Configuration of vitals.xml + additions to messages.properties

config changes vitals SL

---

api/src/main/resources/messages.properties
omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

https://pihemr.atlassian.net/browse/MEX-169

MEX-169 Consult form should have Hypertension section

---

api/src/main/java/org/openmrs/module/pihcore/config/Components.java
api/src/main/resources/messages.properties

MEX-121 Should be able to add CHW as relationship from dashboard
https://pihemr.atlassian.net/browse/MEX-121

MEX-121 Should be able to add CHW as relationship from dashboard

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/GlobalPropertiesBundle.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoMetadataBundle.java

https://pihemr.atlassian.net/browse/MEX-348
depends on https://github.com/PIH/openmrs-module-mirebalaismetadata/pull/26

MEX-348 Connect dummy diagnosis list

---

omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

https://pihemr.atlassian.net/browse/MEX-367

MEX-367 error.noValue when trying to add a diagnosis to the consult form

---

omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

Mostly just formatting, and a comment about how weird it is that we need to do `$j = jq`.

Clean up Mexico Consult JS

---

omod/src/main/webapp/resources/htmlforms/mexico/vitals.xml

Trivial; merging.
https://pihemr.atlassian.net/browse/MEX-301

Put fasting question before glucose measurement

---

omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

Straightforward cleanup of HTML. Added spaces between radio elements. @lnball may be interested. Merging b/c pretty trivial and it doesn't really change anything.

Some minor changes to consult form

---

api/src/main/java/org/openmrs/module/pihcore/config/Components.java

https://pihemr.atlassian.net/browse/MEX-362

MEX-362 Height/weight graph on main patient dashboard

---

api/src/main/java/org/openmrs/module/pihcore/config/Components.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/EncounterTypeBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/core/EncounterTypes.java
api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java
omod/src/main/webapp/resources/htmlforms/sierra_leone/outpatient-followup.xml
omod/src/main/webapp/resources/htmlforms/sierra_leone/outpatient-initial.xml
omod/src/main/webapp/resources/scripts/visit/constants.js
omod/src/main/webapp/resources/scripts/visit/encounterTypeConfig.js

https://pihemr.atlassian.net/browse/SL-88

SL-88 Create new encounter type for Outpatient Visit

---

api/src/main/java/org/openmrs/module/pihcore/PihCoreConstants.java

https://pihemr.atlassian.net/browse/MEX-339
Depends on https://github.com/PIH/openmrs-module-mirebalaismetadata/pull/30

MEX-339 Asthma program should use its own concept, not Chronic Respiratory Disease Program concept

---

omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

Some language fixes for the Mex consult note

---

omod/src/main/webapp/resources/htmlforms/mexico/consult.xml
omod/src/main/webapp/resources/htmlforms/section-plan.xml

Applying the medication form improvement from https://github.com/PIH/openmrs-module-pihcore/pull/74 to PrimaryCare and NCD

Make medication list increment

---

omod/src/main/webapp/resources/htmlforms/section-history.xml

@brandones Do you have time for this?  Otherwise I'll ask someone else.

UHM-3937 Modified the history section for NCD V2

---

omod/src/main/webapp/resources/htmlforms/sierra_leone/vitals.xml

Changes to appearance of added variables - removing bad formatting and adding consistency

cosmetic changes to vitals form

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/concept/SocioEconomicConcepts.java

For https://pihemr.atlassian.net/browse/MEX-404
Fixes problem introduced in https://github.com/PIH/openmrs-module-pihcore/pull/96

Fix duplicate name Ocupación

---

omod/src/main/webapp/resources/htmlforms/sierra_leone/section-anc-followup.xml
omod/src/main/webapp/resources/htmlforms/sierra_leone/section-anc-intake.xml
omod/src/main/webapp/resources/htmlforms/sierra_leone/section-delivery.xml
omod/src/main/webapp/resources/htmlforms/sierra_leone/section-plan.xml

added anc sections and modified family planning question

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoLocationsBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/mexico/MexicoLocations.java
api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java

@lnball , how should we handle this with the Lacolline/Thomonde release? Are you comfortable with this going in the release?

MEX-452 Rename Surgery location to Hospital

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoLocationsBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/mexico/MexicoLocations.java
api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java

https://pihemr.atlassian.net/browse/MEX-447

MEX-447 Split Plan de la Libertad location into Plan Alta and Plan Baja

---

omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

https://pihemr.atlassian.net/browse/MEX-459

MEX-459 "Confirmed" checkbox in Diagnosis wiget should instead say "First time" ("1a vez")

---

api/src/main/java/org/openmrs/module/pihcore/config/registration/ContactInfoConfigDescriptor.java
api/src/main/java/org/openmrs/module/pihcore/config/registration/RegistrationConfigDescriptor.java
api/src/main/java/org/openmrs/module/pihcore/config/registration/RegistrationFieldDescriptor.java
omod/src/main/webapp/resources/htmlforms/liberia/liveCheckin.xml
omod/src/main/webapp/resources/htmlforms/liberia/mentalHealth.xml
pom.xml

- New config descriptor for ContactInfo
- Update dependency of registrationapp to 1.15.0-SNAPSHOT
- New functionality to incorporate regex for phoneNumber field in registration config
- Redirect to  checkin after registration

LIB - Registration app & workflow changes

---

omod/src/main/webapp/resources/htmlforms/sierra_leone/section-anc-followup.xml
omod/src/main/webapp/resources/htmlforms/sierra_leone/section-anc-intake.xml
omod/src/main/webapp/resources/htmlforms/sierra_leone/section-delivery.xml
omod/src/main/webapp/resources/htmlforms/sierra_leone/section-exam.xml
omod/src/main/webapp/resources/htmlforms/sierra_leone/vitals.xml

changes to anc and delivery screens according to requirements, updates to vitals according to SL-124 and SL-133

Sl08pihcore

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/ProviderRoleBundle.java

@mogoodrich @lnball @cioan 
Would you like to review this modification for me please

UHM-4096 Add MH CHW Supervisor provider

---

api/src/main/resources/messages.properties
api/src/main/resources/messages_es.properties
api/src/main/resources/messages_fr.properties
api/src/main/resources/messages_ht.properties

replaced lap order by patient orders

---

omod/src/main/webapp/resources/htmlforms/sierra_leone/section-anc-followup.xml
omod/src/main/webapp/resources/htmlforms/sierra_leone/section-anc-intake.xml
omod/src/main/webapp/resources/htmlforms/sierra_leone/section-delivery.xml
omod/src/main/webapp/resources/htmlforms/sierra_leone/section-plan.xml

removing mental health sections from MCH, adding in requested variables (tear/laceration/suture), improving presentation.
@mogoodrich or @lnball please review

remove mental health sections add variables to delivery

---

api/src/main/resources/messages.properties
omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

Revision: fix message-properties, add units, clean up

MEX-439 Show vitals from the current visit at the top of the consult note (revision)

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoLocationsBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/mexico/MexicoLocations.java
api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java

https://pihemr.atlassian.net/browse/MEX-471

MEX-471 CES cloud server should have "CES Oficina" as a location

---

api/src/main/resources/messages.properties
omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

https://pihemr.atlassian.net/browse/MEX-468

MEX-468 Add "referred by" question to the top of consult note

---

api/src/main/resources/messages.properties
omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

Integrating feedback from https://github.com/PIH/openmrs-module-pihcore/pull/131

MEX-468 Review feedback

---

omod/src/main/webapp/resources/htmlforms/mexico/consult.xml

https://pihemr.atlassian.net/browse/MEX-403

MEX-403 Physical Exam, Analysis, and Clinical Management Plan should show last values on the left

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/RolesAndPrivilegesBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/core/Roles.java
api/src/main/resources/messages.properties
omod/src/main/webapp/resources/htmlforms/liberia/ncd-adult-followup.xml
omod/src/main/webapp/resources/htmlforms/liberia/ncd-adult-initial.xml

- Added COMMUNITY_HEALTH_WORKER role and enabled more Roles in the Liberian deployments
- Updated ncd-initial CHW person role to be community health worker and added i18n property for community health worker privileges

LIB - Added Community health role and updated ncd initial forms

---

api/src/main/resources/messages.properties
omod/src/main/webapp/resources/htmlforms/liberia/ncd-adult-followup.xml
omod/src/main/webapp/resources/htmlforms/liberia/ncd-adult-initial.xml

- LIB - Added COMMUNITY_HEALTH_WORKER role and updated ncd-initial CHW person role to CHW 
- LIB - Removed return visit date from NCD Intake form and updated CKD & HF NCD forms

 LIB - Removed return visit date from NCD Intake form and updated NCD forms

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/liberia/LiberiaLocationsBundle.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/liberia/LiberiaPatientIdentifierTypeBundle.java
api/src/main/java/org/openmrs/module/pihcore/identifier/liberia/ConfigureLiberiaIdGenerators.java
api/src/main/java/org/openmrs/module/pihcore/metadata/liberia/LiberiaLocations.java
api/src/main/java/org/openmrs/module/pihcore/metadata/liberia/LiberiaPatientIdentifierTypes.java
api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java

- Added Patient Identifier Type for Mental health MRN
- Update MH_MRN name to properly display on patient header
- Setup location tags and new login locations.

LIB - Setup new patient identifer type and locations (session locations)

---

api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java

LIB - Enable labResults for OPD and NCD clinics

LIB - Enable labResults for OPD and NCD clinics

---

pom.xml

Everything seems to be working on my local server, and tests are passing.
https://pihemr.atlassian.net/browse/UHM-4411

Bump pihcore Java version to 8

---

api/src/main/java/org/openmrs/module/pihcore/PihCoreActivator.java
api/src/main/java/org/openmrs/module/pihcore/PihCoreUtil.java
api/src/main/java/org/openmrs/module/pihcore/setup/DrugListSetup.java
api/src/test/java/org/openmrs/module/pihcore/setup/DrugListSetupTest.java
api/src/test/resources/testAppDataDir/configuration/pih/drugs/drugs.csv

https://pihemr.atlassian.net/browse/UHM-4268

UHM-4268 Move Drug Lists into openmrs-config-pihemr repos

---

api/src/main/resources/messages.properties

LIB - i18n mircrobiology

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/liberia/LiberiaMetadataBundle.java

LIB - Added orderentryowa.labOrderablesConceptSet & labworkflowowa.locationOfLaboratory

LIB - Added orderentryowa.labOrderablesConceptSet & labworkflowowa.locationOfLaboratory

---

omod/src/main/webapp/pages/visit/templates/encounters/defaultEncounterHeading.gsp
omod/src/main/webapp/pages/visit/templates/encounters/edTriageEncounterHeading.gsp
omod/src/main/webapp/pages/visit/templates/encounters/pathologySpecimenCollectionLong.gsp
omod/src/main/webapp/pages/visit/templates/sections/defaultSectionHeading.gsp
omod/src/main/webapp/pages/visit/templates/showEncounterDetails.gsp
omod/src/main/webapp/resources/scripts/visit/filters.js

fix display of provider if identifier is missing

UHM-4489: Multiple CommCare Integration users on HUM-CI

---

api/src/main/resources/liquibase.xml

@mogoodrich Apologies if I got this wrong, but I do PR's so infrequently that I need a better cheat sheet than this...https://wiki.openmrs.org/display/docs/Pull+Request+Tips
That's why I'm a /dev/1

UHM-4626 Fix duplicate skin exam concept

---

api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java

UHM-4647 Added all clinical areas at HUM; LocationTags for COVID

---

api/src/main/resources/sql/procedures/create_functions.sql

Create new functions for SL-176 Create functions for obs by visit, obs_group.
Just creating 2 functions for first PR (value coded for visit and obs_group).  If these look good, I can create the others (number, test etc...)

SL-176 -Create functions for obs by visit, obs_group

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoLocationsBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/mexico/MexicoLocations.java

https://pihemr.atlassian.net/browse/MEX-495

Add Casa Materna and CER locations for CES

---

api/src/main/java/org/openmrs/module/pihcore/metadata/mexico/MexicoLocations.java

trivial; a mistake from #201 .

Change CASA_MATERNA uuid to be different from CER

---

api/src/main/java/org/openmrs/module/pihcore/metadata/core/program/HIVProgram.java

https://pihemr.atlassian.net/browse/UHM-3122

UHM-3122 Removing HIV Program workflow

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/haiti/PihHaitiPatientIdentifierTypeBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/haiti/PihHaitiPatientIdentifierTypes.java
pom.xml

@mogoodrich , here are the changes I had to make in the pihcore to be able to set the unique property on the PatientIdentifierType. This goes with the metadatadeploy PR:
https://github.com/openmrs/openmrs-module-metadatadeploy/pull/12
Thanks!

UHM-4880, install PatientIdentifierType with UniquenessBehavior

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/haiti/PihHaitiPatientIdentifierTypeBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/haiti/PihHaitiPatientIdentifierTypes.java

@mogoodrich , here is the commit for configuring National ID and Fiscal ID. Thanks!

UHM-4881, configure national and fiscal IDs

---

api/src/main/java/org/openmrs/module/pihcore/PihCoreConstants.java
api/src/main/java/org/openmrs/module/pihcore/metadata/core/program/HIVProgram.java

https://pihemr.atlassian.net/browse/UHM-4977

Add workflows to HIV program

---

api/src/main/java/org/openmrs/module/pihcore/metadata/core/program/OVCProgram.java

https://pihemr.atlassian.net/browse/UHM-4986

UHM-4986 OVC Program config

---

api/src/main/java/org/openmrs/module/pihcore/PihCoreConstants.java

Package update: https://github.com/PIH/openmrs-config-pihemr/commit/a8b45b20fc20c64506664e7f08fd167276c9b7eb

Update OVC program state concepts

---

api/src/main/java/org/openmrs/module/pihcore/config/Components.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/EncounterTypeBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/core/EncounterTypes.java

https://pihemr.atlassian.net/browse/PER-351
Message code for new ET: https://github.com/PIH/openmrs-config-pihemr/commit/21784400d46ab5d65a96922c766b9971eba0986b

Split HIV and COVID components. Create TB component, along with Form and EncounterType

---

api/src/main/java/org/openmrs/module/pihcore/PihCoreActivator.java
api/src/main/java/org/openmrs/module/pihcore/setup/NameTemplateSetup.java

First time doing a pull request, sorry for taking so much time.
I added the "familyName2" in the first IF, i added it also on the second to force it but got no results.
PD: Forgot to delete the "familyName2" on the second IF

Peru name template

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/liberia/LiberiaLocationsBundle.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/liberia/LiberiaPatientIdentifierTypeBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/liberia/LiberiaLocations.java
api/src/main/java/org/openmrs/module/pihcore/metadata/liberia/LiberiaPatientIdentifierTypes.java

NCD clinic requested an MRN. A location for Phamarcy was also added.
fyi @mogoodrich @lnball @brandones

phamarcy location and ncd mrn added

---

api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoPatientIdentifierTypeBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/mexico/MexicoPatientIdentifierTypes.java

https://github.com/PIH/openmrs-config-ces/pull/16
https://pihemr.atlassian.net/browse/MEX-498

Create Mexico Dossier Number ID type

---

api/src/main/java/org/openmrs/module/pihcore/PihCoreConstants.java
api/src/main/java/org/openmrs/module/pihcore/identifier/haiti/ConfigureHaitiIdGenerators.java
api/src/main/java/org/openmrs/module/pihcore/identifier/mexico/ConfigureMexicoIdGenerators.java

https://pihemr.atlassian.net/browse/MEX-498

Configure Dossier number generator for Mexico

---

pom.xml

https://github.com/PIH/openmrs-module-mirebalais/pull/136

Upgrade to registrationapp 1.23.0-SNAPSHOT

---

omod/src/main/webapp/fragments/allergyui/addNextButton.gsp
omod/src/main/webapp/pages/checkin/checkin.gsp
omod/src/main/webapp/pages/export/exportPatients.gsp
omod/src/main/webapp/pages/export/importPatients.gsp
omod/src/main/webapp/pages/visit/templates/encounters/checkInEncounterHeading.gsp
omod/src/main/webapp/pages/visit/templates/encounters/clinicConsultLong.gsp
omod/src/main/webapp/pages/visit/templates/encounters/defaultEncounterHeading.gsp
omod/src/main/webapp/pages/visit/templates/encounters/vitalsEncounterHeading.gsp
omod/src/main/webapp/pages/visit/templates/sections/defaultSectionHeading.gsp
omod/src/main/webapp/pages/visit/templates/sections/dxLong.gsp
omod/src/main/webapp/pages/visit/templates/showEncounterDetails.gsp
omod/src/main/webapp/pages/visit/templates/vaccination/vaccinationsPage.gsp

https://issues.openmrs.org/browse/RA-1898

RA-1898 Change all 'emr.' message codes to 'coreapps.' equivalents

---

omod/src/main/java/org/openmrs/module/pihcore/page/controller/meds/DrugOrdersPageController.java
omod/src/main/webapp/pages/meds/drugOrders.gsp

uhm-5333 - add comments to drug orders page

---

api/src/main/java/org/openmrs/module/pihcore/config/Components.java
api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/core/EncounterTypeBundle.java
api/src/main/java/org/openmrs/module/pihcore/metadata/core/EncounterTypes.java

https://pihemr.atlassian.net/browse/UHM-5315

UHM-5315 Add Clinical Note encounter type and form

---

api/src/main/java/org/openmrs/module/pihcore/PihCoreUtil.java

@mogoodrich, this seems to take care of the Windows path issue.

UHM-5533, encode file path

---

omod/src/main/java/org/openmrs/module/pihcore/page/controller/peru/AnalysisRequestsPageController.java
omod/src/main/webapp/pages/peru/analysisRequests.gsp

Added date range in the gui and a link per patient to a sampleCollection.

Lab order list modified

---

api/src/test/java/org/openmrs/module/pihcore/MirebalaisActivatorTest.java
api/src/test/java/org/openmrs/module/pihcore/PihCoreActivatorTest.java
api/src/test/resources/testAppDataDir/configuration/relationshiptypes/pih.csv

Fix tests after RelationshipType migrated to config-pihemr

---

omod/src/main/webapp/pages/visit/templates/visitDetailsEdit.gsp
omod/src/main/webapp/pages/visit/visit.gsp
omod/src/main/webapp/resources/scripts/visit/visit.js

https://pihemr.atlassian.net/browse/UHM-5753

UHM-5753 Allow changing visit location; remove usages of `$filter('serverDate')`

---

api/src/main/resources/liquibase.xml

I have already update the form here:
https://github.com/PIH/openmrs-config-pihsl/commit/002768fd0e896374446aa9aef0c23b6616bc6d9d

UHM-5771, change concept PIH:SEXUALLY ACTIVE datatype to Coded

---

omod/src/main/webapp/resources/scripts/visit/visit.js

Trivial; merging
https://pihemr.atlassian.net/browse/UHM-5753

Fix date parsing

---

omod/src/main/webapp/pages/visit/templates/encounters/encounterList.gsp
omod/src/main/webapp/resources/scripts/visit/visit.js

Just added two icons next to each encounter row that allows us to edit and delete an encounter.

UHM-5400, add edit and delete encounter icons

---

omod/src/main/webapp/resources/scripts/visit/filters.js
omod/src/main/webapp/resources/scripts/visit/visit.js

See https://github.com/openmrs/openmrs-module-coreapps/pull/438

Add patient encounters to context model

---

omod/src/main/webapp/resources/scripts/visit/visit.js

Before, the UI would sometimes fail to update after a state change. Now it seems to work consistently.
Follow-up to https://github.com/PIH/openmrs-module-pihcore/pull/319
Related to https://github.com/openmrs/openmrs-module-coreapps/pull/438
Ticket https://pihemr.atlassian.net/browse/UHM-5851

Improve behavior for fetching historical encounters in visits app

---

omod/src/main/webapp/pages/visit/templates/encounters/checkInEncounterHeading.gsp
omod/src/main/webapp/pages/visit/templates/encounters/clinicConsultLong.gsp
omod/src/main/webapp/pages/visit/templates/encounters/defaultEncounterHeading.gsp
omod/src/main/webapp/pages/visit/templates/encounters/edTriageEncounterHeading.gsp
omod/src/main/webapp/pages/visit/templates/encounters/pathologySpecimenCollectionLong.gsp
omod/src/main/webapp/pages/visit/templates/encounters/vitalsEncounterHeading.gsp
omod/src/main/webapp/pages/visit/templates/orders/old/orderSheet.gsp
omod/src/main/webapp/pages/visit/templates/sections/defaultSectionHeading.gsp
omod/src/main/webapp/pages/visit/templates/showEncounterDetails.gsp
omod/src/main/webapp/pages/visit/templates/visitDetails.gsp
omod/src/main/webapp/resources/scripts/reports/activeVisitsListController.js

Depends on https://github.com/openmrs/openmrs-module-uicommons/pull/99

Use the serverDateLocalized function to render dates and times

---

api/src/main/java/org/openmrs/module/pihcore/setup/InitializerSetup.java

(Add Concepts to the list of metadata to be loaded *after* concepts)

PER-406: Unable to set up new Peru dev environment from scratch

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java

Fix report configuration in the CALF

UHM-6151: HUM EMR is slow

---

omod/src/main/webapp/pages/patient/encounterList.gsp

UHM-6129:patient saved forms list page

---

api/src/main/java/org/openmrs/module/pihcore/htmlformentry/action/ExitPatientFromSelectedProgramsAction.java

[MEX-517](https://pihemr.atlassian.net/browse/MEX-517)

MEX-517: Auto update program status from form

---

pom.xml

Updating ui commons version in pom.xml.
The new version of ui commons has the capability to add external link

Update ui-commons after adding capability for external link

---

omod/src/main/java/org/openmrs/module/pihcore/page/controller/visit/TodaysVisitsPageController.java
omod/src/main/webapp/pages/visit/todaysVisits.gsp

@mogoodrich please review this PR

HAI-666: display the queue of visits by user's location

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java

Adding of viral load history section to HIV patient dashboard.

Add viral load history section to patient hiv dashboard

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java

Update Viral load history header label

Hai 694 add viral load history last three recent viral load and their outcome

---

omod/src/main/java/org/openmrs/module/pihcore/page/controller/visit/TodaysVisitsPageController.java
omod/src/main/webapp/pages/visit/todaysVisits.gsp

@mogoodrich Please review this PR

Hai 666 filter the patient queues by site

---

omod/src/main/java/org/openmrs/module/pihcore/page/controller/account/ChangePasswordPageController.java
omod/src/main/java/org/openmrs/module/pihcore/page/controller/account/ChangeSecurityQuestionPageController.java
omod/src/main/java/org/openmrs/module/pihcore/page/controller/account/MyAccountPageController.java
omod/src/main/webapp/pages/account/changePassword.gsp
omod/src/main/webapp/pages/account/changeSecurityQuestion.gsp
omod/src/main/webapp/pages/account/myAccount.gsp
pom.xml

UHM-6804 - Enable users to administer their security question/answer

---

api/src/main/java/org/openmrs/module/pihcore/task/PihCoreScheduledTaskExecutor.java

@mseaton  was reminded of this while looking at your changes to close stale visits and wanted to just get it in before I forgot

have stale visits task only run once an hour

---

pom.xml

I would like to just merge this in, but just putting in a PR in case we are being conservative prior to gold.

UHM-7120: Upgrade webservices version to support condition resource

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/pihcore/apploader/apps/patientregistration/SectionsLiberia.java

This is to remove the Patient support (CHW) questions from Liberia registration (ughhh) since it's now in check-in.

LIB-242 Removed patient support section for Liberia registration

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java

Please @mseaton review this PR

Mental Health status section added to patient dashboard

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/pihcore/apploader/apps/GraphFactory.java

Display CGI Scores on the dashboard

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java
omod/src/main/java/org/openmrs/module/pihcore/fragment/controller/dashboardwidgets/LabResultsFragmentController.java
omod/src/main/webapp/fragments/dashboardwidgets/labResults.gsp

@mogoodrich , here is the PR for creating a new dashboard widget. Thanks!

UHM-7254, add dashboard widget to display recent lab results

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/pihcore/config/Components.java
omod/src/main/java/org/openmrs/module/pihcore/fragment/controller/hiv/ProgramLocationWarningFragmentController.java
omod/src/main/webapp/fragments/hiv/programLocationWarning.gsp

@cioan have a look on it. it is not showing in the alert.

Creating another branch to prevent code break in branch HAI-753

---

omod/src/main/webapp/fragments/hiv/programLocationWarning.gsp

@dmdesimone addig the translated messge to the ui. Have a look please

addig the translated messge to the ui

---

omod/src/main/webapp/fragments/hiv/programLocationWarning.gsp

@cioan I make a little change. have a quick look please

fixing an issue

---

api/src/main/java/org/openmrs/module/pihcore/status/StatusDataEvaluator.java

configuring locale

---

omod/src/main/webapp/pages/visit/templates/overview.gsp
omod/src/main/webapp/pages/visit/templates/queue/queueEntry.gsp
omod/src/main/webapp/pages/visit/visit.gsp
omod/src/main/webapp/resources/scripts/services/queueEntryService.js
omod/src/main/webapp/resources/scripts/visit/constants.js
omod/src/main/webapp/resources/scripts/visit/visit.js
omod/src/main/webapp/resources/styles/visit/visit.scss

See https://pihemr.atlassian.net/browse/UHM-7422

UHM-7422 - View a history of visit statuses within a visit summary

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/pihcore/config/Components.java

Added MCOE Triage visit action.

SL-553: Add MCOE triage form and visit action

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java
omod/src/main/java/org/openmrs/module/pihcore/fragment/controller/dashboardwidgets/AppointmentsFragmentController.java
omod/src/main/webapp/fragments/dashboardwidgets/appointments.gsp

(change logic to show only scheduled or checked-in appointments but across *all* dates)

UHM-7757: View Patient Appointments Via O2 Patient Chart

---

omod/src/main/java/org/openmrs/module/pihcore/page/controller/children/ChildrenPageController.java
omod/src/main/webapp/pages/children/children.gsp

Just listing patient's children, as they are defined by the Mother-to-Child relationship:

SL-613, list patient's children

---

omod/src/main/java/org/openmrs/module/pihcore/page/controller/children/ChildrenPageController.java
omod/src/main/webapp/pages/children/children.gsp

SL-616, delete child relationship

---

omod/src/main/java/org/openmrs/module/pihcore/page/controller/children/FindChildrenPageController.java
omod/src/main/webapp/pages/children/children.gsp
omod/src/main/webapp/pages/children/findChildren.gsp

This allows the user to search for an existing child and to create a new mother-child relationship:

SL-615: Search for existing child

---

omod/src/main/java/org/openmrs/module/pihcore/page/controller/children/FindChildrenPageController.java
omod/src/main/webapp/pages/children/findChildren.gsp

Finally, got all mother's requested info into the child registration page:

SL-614: use mother's address when registering a child

---

omod/src/main/java/org/openmrs/module/pihcore/page/controller/children/ChildrenPageController.java
omod/src/main/webapp/pages/children/children.gsp

@mogoodrich , here is the Unregistered Babies table that display the Labour and Delivery encounters with "Baby registered in EMR" obs set to No:

SL-617: build the Unregistered Babies table

---

omod/src/main/java/org/openmrs/module/pihcore/page/controller/children/ChildrenPageController.java
omod/src/main/java/org/openmrs/module/pihcore/page/controller/children/FindChildrenPageController.java
omod/src/main/webapp/pages/children/children.gsp

@mogoodrich, this PR is not complete yet, but I was able to implement one use case of the process of linking a registered baby to the labor and delivery form. I will add some screenshots and more comments to the ticket so everyone could follow along. In this PR I also addressed the latest issues Fiona raised in SL-683(new verbiage) and SL-684(order children by age). Thanks!

SL-619: link registered babies to labor and delivery encounter

---

omod/src/main/webapp/pages/children/children.gsp

@mogoodrich , this is just implementing the remove delivery from the unregistered babies table:

SL:688: remove delivery from the unregistered babies table

---

omod/src/main/java/org/openmrs/module/pihcore/page/controller/children/FindChildrenPageController.java
omod/src/main/webapp/pages/children/children.gsp
omod/src/main/webapp/pages/children/findChildren.gsp

@mogoodrich , finally I was able to complete this new feature end-to-end. Now the code checks if the selected baby is already linked to the mother and highlights that entry. Also, it allows to search and select any registered patient in the system:

SL-619: linking existing patient to labour and delivery encounter

---

omod/src/main/webapp/pages/children/children.gsp
omod/src/main/webapp/resources/scripts/wristband/printWristband.js

This turned out to be pretty easy, I just modified the javascript printWristband function to accept an optional parameter:

SL-700: print wristband from within the children page

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/pihcore/config/Components.java

This goes with 2 other PRs:  https://pihemr.atlassian.net/browse/UHM-8109

UHM_8109 Changed component name and rehab to physicalRehab

---

api/src/main/java/org/openmrs/module/pihcore/htmlformentry/action/RegisterBabyAction.java

This seems to be working fine:

SL-701: create visit and admission encounter for newly registered babies

---

api/src/main/java/org/openmrs/module/pihcore/htmlformentry/action/PregnancyProgramEnrollmentAction.java
api/src/main/java/org/openmrs/module/pihcore/htmlformentry/action/PregnancyProgramPostpartumTransitionAction.java
api/src/main/java/org/openmrs/module/pihcore/htmlformentry/action/util/PregnancyProgramActionUtils.java
api/src/test/java/org/openmrs/module/pihcore/htmlformentry/action/PregnancyProgramEnrollmentActionTest.java
api/src/test/java/org/openmrs/module/pihcore/htmlformentry/action/PregnancyProgramPostpartumTransitionActionTest.java
api/src/test/resources/pregnancyProgramActionTestDataset.xml

SL-669: Auto-update Program State from forms

SL-667: Auto enrollment in the Pregnancy Program from a form

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java

@mogoodrich , here is the only change I made to the CALF to point to the new program summary page.

SL-671: redirect to a new program summary page

---

omod/src/main/java/org/openmrs/module/pihcore/fragment/controller/dashboardwidgets/PatientLocationFragmentController.java
omod/src/main/webapp/fragments/dashboardwidgets/patientLocation.gsp

@mogoodrich and @mseaton , I got this patient location widget to display the status and location as we discussed yesterday:

SL-733: add patient location widget

---

omod/src/main/java/org/openmrs/module/pihcore/fragment/controller/dashboardwidgets/ObsByEncounterFragmentController.java
omod/src/main/webapp/fragments/dashboardwidgets/obsByEncounter.gsp

@mseaton and @mogoodrich , here is the new "headers" config parameter for this widget. Thanks!

SL-735: add headers column config parameter

---

api/src/main/java/org/openmrs/module/pihcore/htmlformentry/action/RegisterBabyAction.java

[Ticket](https://pihemr.atlassian.net/browse/UHM-8183)
On completion of Labour and Delivery Summary form, we assign the newborn to the mother's bed. 
Testing done:
- admit a mother to a ward and assign her a bed. Fill out the Labour and Delivery Summary form to create a newborn. Verify that the newborn is admitted to the same ward and assigned the same bed as the mother.

UHM-8183 on register, assign newborn to mother's bed

---

omod/src/main/java/org/openmrs/module/pihcore/PihCoreUtils.java
omod/src/main/java/org/openmrs/module/pihcore/fragment/controller/dashboardwidgets/DiscreteValuesFragmentController.java
omod/src/main/java/org/openmrs/module/pihcore/fragment/controller/dashboardwidgets/NewbornIndicatorsFragmentController.java
omod/src/main/java/org/openmrs/module/pihcore/fragment/controller/dashboardwidgets/PatientLocationFragmentController.java
omod/src/main/webapp/fragments/dashboardwidgets/discreteValues.gsp
omod/src/main/webapp/fragments/dashboardwidgets/newbornIndicators.gsp

Since the Newborn Indicators widget is required to display the patient location, I have moved the code from the Patient Location widget into a common class that both widgets could invoke.

SL-742: implement Newborn Indicators widget

---

omod/src/main/java/org/openmrs/module/pihcore/PihCoreUtils.java
omod/src/main/java/org/openmrs/module/pihcore/fragment/controller/dashboardwidgets/PregnancyIndicatorsFragmentController.java
omod/src/main/webapp/fragments/dashboardwidgets/pregnancyIndicators.gsp

Here is the new Pregnancy Indicators widget, as it was mocked on the SL-731 ticket:

SL-731: add pregnancy indicators widget

---

api/src/main/java/org/openmrs/module/pihcore/printer/template/SLWristbandTemplate.java
api/src/test/java/org/openmrs/module/pihcore/printer/template/SLWristbandTemplateTest.java

https://pihemr.atlassian.net/browse/UHM-7589

UHM-7859: create MCOE wristbands (on demand)

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java

Add lab results on HIV patient chart

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java

HAI-1024-update:  breadcrumbs now correctly navigate back to patient dashboard from full lab results

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java

@mogoodrich Can you confirm that this looks right?  I cannot test fully on my SDK because I don't have a fingerprint reader.  If it looks somewhat correct, please merge.  Then I can test on a server with fingerprints (ie. haitihivtest or humci)

HAI-1035 Added biometrics widget to the HIV dashboard

---

omod/src/main/java/org/openmrs/module/pihcore/fragment/controller/dashboardwidgets/PregnancyIndicatorsFragmentController.java

@mogoodrich , just calculating the due date based on the gestational age and the obs datetime. Thanks!

SL-884: calculate due date base on the gestational age

---

api/src/main/java/org/openmrs/module/pihcore/htmlformentry/action/RegisterBabyAction.java

@mogoodrich , just creating a Registration encounter and updating the default Infant name. Thanks!

SL-931: create registration encounter for the infant

---

omod/src/main/java/org/openmrs/module/pihcore/page/controller/admin/RolesAndPrivilegesPageController.java
omod/src/main/webapp/pages/admin/rolesAndPrivileges.gsp

@mogoodrich , this is just a simple expandable list to view all roles and privileges:

UHM-8544: add page to view roles and privileges

---

api/src/main/java/org/openmrs/module/pihcore/htmlformentry/action/RegisterBabyAction.java

@mogoodrich , this is just adding the log on user, the user who fills in the labour and delivery form as the provider of the baby's registration encounter. Thanks!

SL-931: add the current log on user as the provider of the registration encounter

---

api/src/main/java/org/openmrs/module/pihcore/service/PihCoreServiceImpl.java

HAI-736: Afficher le site auquel appartient un patient lors de la recherche

---

api/src/main/java/org/openmrs/module/pihcore/apploader/CustomAppLoaderFactory.java
omod/src/main/java/org/openmrs/module/pihcore/fragment/controller/dashboardwidgets/FingerprintFragmentController.java
omod/src/main/webapp/fragments/dashboardwidgets/fingerprint.gsp

HAI-1078:Fingerprint widget on registration dashboard with HIV dashboard widget
